# Generated by Django 5.2.9 on 2025-12-08 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaKullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=100)),
                ('onaylandi', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmsalKarar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('ozet', models.TextField()),
                ('dosya_linki', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HukukKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ikon', models.CharField(default='⚖️', max_length=50)),
                ('aciklama', models.TextField(blank=True)),
                ('ai_talimati', models.TextField(help_text='Bu kategorideki AI botuna verilecek özel gizli talimat.')),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField()),
                ('ozellikler', models.TextField(help_text='Her satıra bir özellik yazın')),
            ],
        ),
        migrations.CreateModel(
            name='ReklamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Reklam Adı (Örn: Sol Taraf)')),
                ('gorsel', models.ImageField(upload_to='reklamlar/', verbose_name='Reklam Görseli')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Tıklanınca Gideceği Link')),
                ('pozisyon', models.CharField(choices=[('Sol', 'Sol'), ('Sag', 'Sag')], max_length=10, verbose_name='Sayfadaki Yeri')),
                ('genislik', models.PositiveIntegerField(default=160, editable=False, verbose_name='Genişlik (px)')),
                ('yukseklik', models.PositiveIntegerField(default=600, editable=False, verbose_name='Yükseklik (px)')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Sitede Görünsün mü?')),
            ],
        ),
        migrations.CreateModel(
            name='SistemBildirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('okundu_mu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('seviye', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('danger', 'Acil')], default='info', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_basligi', models.CharField(default='L.E.X.I.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('font_baslik', models.CharField(choices=[('Inter', 'Inter (Modern & Temiz)'), ('Roboto', 'Roboto (Standart & Okunaklı)'), ('Open Sans', 'Open Sans (Ferah & Açık)'), ('Lato', 'Lato (Yuvarlak & Samimi)'), ('Montserrat', 'Montserrat (Geometrik & Güçlü)'), ('Raleway', 'Raleway (Zarif & İnce)'), ('Poppins', 'Poppins (Popüler & Yuvarlak)'), ('Playfair Display', 'Playfair Display (Tırnaklı & Klasik)'), ('Merriweather', 'Merriweather (Okuma Odaklı)'), ('Lora', 'Lora (Hukuki & Ciddi)'), ('Oswald', 'Oswald (Dik & Sıkışık)'), ('Rubik', 'Rubik (Yumuşak Köşeli)')], default='Inter', max_length=100)),
                ('font_genel', models.CharField(choices=[('Inter', 'Inter (Modern & Temiz)'), ('Roboto', 'Roboto (Standart & Okunaklı)'), ('Open Sans', 'Open Sans (Ferah & Açık)'), ('Lato', 'Lato (Yuvarlak & Samimi)'), ('Montserrat', 'Montserrat (Geometrik & Güçlü)'), ('Raleway', 'Raleway (Zarif & İnce)'), ('Poppins', 'Poppins (Popüler & Yuvarlak)'), ('Playfair Display', 'Playfair Display (Tırnaklı & Klasik)'), ('Merriweather', 'Merriweather (Okuma Odaklı)'), ('Lora', 'Lora (Hukuki & Ciddi)'), ('Oswald', 'Oswald (Dik & Sıkışık)'), ('Rubik', 'Rubik (Yumuşak Köşeli)')], default='Inter', max_length=100)),
                ('renk_ana', models.CharField(default='#0071e3', max_length=20, verbose_name='Ana Vurgu Rengi (Mavi vb.)')),
                ('renk_arkaplan_light', models.CharField(default='#f5f5f7', max_length=20, verbose_name='Açık Mod Arkaplan')),
                ('renk_yazi_light', models.CharField(default='#1d1d1f', max_length=20, verbose_name='Açık Mod Yazı')),
                ('renk_kart_light', models.CharField(default='#ffffff', max_length=20, verbose_name='Açık Mod Kart Rengi')),
                ('renk_arkaplan_dark', models.CharField(default='#202020', max_length=20, verbose_name='Koyu Mod Arkaplan')),
                ('renk_yazi_dark', models.CharField(default='#f5f5f7', max_length=20, verbose_name='Koyu Mod Yazı')),
                ('renk_kart_dark', models.CharField(default='#1c1c1e', max_length=20, verbose_name='Koyu Mod Kart Rengi')),
            ],
        ),
        migrations.CreateModel(
            name='SohbetGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField()),
                ('cevap', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avukat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='avukatlar/')),
                ('uzmanlik', models.CharField(max_length=100)),
                ('ozet', models.TextField()),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvukatRandevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('eposta', models.EmailField(max_length=254)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Bekliyor', max_length=20)),
                ('avukat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avukat')),
            ],
        ),
        migrations.CreateModel(
            name='KanunMaddesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanun_adi', models.CharField(max_length=200)),
                ('madde_no', models.CharField(max_length=50)),
                ('icerik', models.TextField()),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hukukkategori')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('eposta', models.EmailField(max_length=254)),
                ('notlar', models.TextField(blank=True)),
                ('odendi_mi', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paket')),
            ],
        ),
        migrations.CreateModel(
            name='VeriGuncellemeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('eklenen_veri_sayisi', models.IntegerField(default=0)),
                ('basarili_mi', models.BooleanField(default=True)),
                ('hata_mesaji', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hukukkategori')),
            ],
        ),
    ]
