# Generated by Django 6.0 on 2025-12-06 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanunMaddesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madde_no', models.CharField(max_length=90)),
                ('konu', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.CharField(max_length=50)),
                ('ozellikler', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_basligi', models.CharField(default='LegalAI', max_length=100, verbose_name='Site Başlığı (Sol Üstte Yazan)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Site Logosu')),
                ('renk_ana', models.CharField(default='#003366', max_length=20, verbose_name='Ana Renk (Çizgiler, Kenarlıklar, Vurgular)')),
                ('renk_arkaplan', models.CharField(default='#FDFBF7', max_length=20, verbose_name='Tüm Sayfa Arka Plan Rengi')),
                ('renk_menu_bg', models.CharField(default='#ffffff', max_length=20, verbose_name='Üst Menü Arka Planı (Navbar)')),
                ('renk_yazi_baslik', models.CharField(default='#003366', max_length=20, verbose_name='Büyük Başlık Rengi (H1, H2)')),
                ('renk_yazi_genel', models.CharField(default='#333333', max_length=20, verbose_name='Genel Yazı Rengi (Paragraflar)')),
                ('renk_buton', models.CharField(default='#003366', max_length=20, verbose_name='Buton Rengi (Satın Al, Gönder)')),
                ('renk_ai_balon', models.CharField(default='#ffffff', max_length=20, verbose_name='Yapay Zeka Cevap Kutusu Rengi')),
                ('renk_user_balon', models.CharField(default='#f0f0f0', max_length=20, verbose_name='Kullanıcı Mesaj Balonu Rengi')),
                ('renk_input_bg', models.CharField(default='#ffffff', max_length=20, verbose_name='Soru Yazma Kutusu (Input) Rengi')),
                ('font_baslik', models.CharField(choices=[('Times New Roman', 'Times New Roman (Klasik)'), ('Playfair Display', 'Playfair Display (Elit & Şık)'), ('Merriweather', 'Merriweather (Okunaklı Kitap Havası)'), ('Lora', 'Lora (Hukuki & Zarif)'), ('Segoe UI', 'Segoe UI (Modern Standart)'), ('Roboto', 'Roboto (Google Standardı - Net)'), ('Open Sans', 'Open Sans (Ferah & Açık)'), ('Montserrat', 'Montserrat (Güçlü Başlıklar İçin)'), ('Poppins', 'Poppins (Geometrik & Yeni Nesil)'), ('Oswald', 'Oswald (Dikkat Çekici Uzun)')], default='Playfair Display', max_length=50, verbose_name='Başlık Yazı Tipi')),
                ('font_genel', models.CharField(choices=[('Times New Roman', 'Times New Roman (Klasik)'), ('Playfair Display', 'Playfair Display (Elit & Şık)'), ('Merriweather', 'Merriweather (Okunaklı Kitap Havası)'), ('Lora', 'Lora (Hukuki & Zarif)'), ('Segoe UI', 'Segoe UI (Modern Standart)'), ('Roboto', 'Roboto (Google Standardı - Net)'), ('Open Sans', 'Open Sans (Ferah & Açık)'), ('Montserrat', 'Montserrat (Güçlü Başlıklar İçin)'), ('Poppins', 'Poppins (Geometrik & Yeni Nesil)'), ('Oswald', 'Oswald (Dikkat Çekici Uzun)')], default='Open Sans', max_length=50, verbose_name='Genel Yazı Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='SohbetGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(verbose_name='Kullanıcı Sorusu')),
                ('cevap', models.TextField(verbose_name='AI Cevabı')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='Avukat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('uzmanlik', models.CharField(max_length=100)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='avukatlar/')),
                ('ozet', models.TextField(blank=True, verbose_name='Biyografi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
        ),
        migrations.CreateModel(
            name='AvukatRandevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('mesaj', models.TextField(blank=True, verbose_name='Konuşulacak Konu/Not')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Görüşüldü', 'Görüşüldü'), ('İptal', 'İptal')], default='Bekliyor', max_length=20)),
                ('avukat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avukat', verbose_name='Seçilen Avukat')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.TextField(blank=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('odendi_mi', models.BooleanField(default=False)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paket')),
            ],
        ),
    ]
