# Generated by Django 5.2.9 on 2025-12-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavaAnalizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daire', models.CharField(blank=True, max_length=100, verbose_name='Daire')),
                ('esas_no', models.CharField(blank=True, max_length=50, verbose_name='Esas No')),
                ('karar_no', models.CharField(blank=True, max_length=50, verbose_name='Karar No')),
                ('karar_tarihi', models.CharField(blank=True, max_length=50, verbose_name='Tarih')),
                ('baslik', models.CharField(max_length=255, verbose_name='Dava Başlığı')),
                ('ozet_hikaye', models.TextField(blank=True, verbose_name='Özet Hikaye')),
                ('hukuki_ilke', models.TextField(blank=True, verbose_name='Hukuki İlke')),
                ('kritik_uyari', models.TextField(blank=True, verbose_name='Kritik Uyarı')),
                ('hukum_sonucu', models.CharField(blank=True, max_length=100, verbose_name='Sonuç')),
                ('konu_etiketleri', models.JSONField(blank=True, default=list, verbose_name='Etiketler')),
                ('dosya_adi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Kaynak Dosya')),
                ('dosya_linki', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dava Analizi (AI)',
                'verbose_name_plural': 'Dava Analizleri (AI)',
            },
        ),
        migrations.DeleteModel(
            name='EmsalKarar',
        ),
        migrations.AlterModelOptions(
            name='avukat',
            options={'verbose_name': 'Avukat', 'verbose_name_plural': 'Avukatlar'},
        ),
        migrations.AlterModelOptions(
            name='avukatrandevu',
            options={'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterModelOptions(
            name='betakullanici',
            options={'verbose_name': 'Beta Kullanıcı Başvurusu', 'verbose_name_plural': 'Beta Kullanıcı Başvuruları'},
        ),
        migrations.AlterModelOptions(
            name='hukukkategori',
            options={'verbose_name': 'Hukuk Kategorisi', 'verbose_name_plural': 'Hukuk Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='kanunmaddesi',
            options={'verbose_name': 'Kanun Maddesi', 'verbose_name_plural': 'Kanun Maddeleri'},
        ),
        migrations.AlterModelOptions(
            name='reklambanner',
            options={'verbose_name': 'Reklam Banner', 'verbose_name_plural': 'Reklam Bannerları'},
        ),
        migrations.AlterModelOptions(
            name='siparis',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='sistembildirimi',
            options={'verbose_name': 'Sistem Bildirimi', 'verbose_name_plural': 'Sistem Bildirimleri'},
        ),
        migrations.AlterModelOptions(
            name='siteayarlari',
            options={'verbose_name': 'Site Ayarları', 'verbose_name_plural': 'Site Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='sohbetgecmisi',
            options={'verbose_name': 'Sohbet Kaydı', 'verbose_name_plural': 'Sohbet Geçmişi'},
        ),
        migrations.AddField(
            model_name='davaanalizi',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='davalar', to='core.hukukkategori'),
        ),
        migrations.AlterUniqueTogether(
            name='davaanalizi',
            unique_together={('daire', 'esas_no', 'karar_no')},
        ),
    ]
