# Generated by Django 6.0 on 2025-12-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Reklam Adı (Örn: Coca Cola)')),
                ('resim', models.ImageField(upload_to='reklamlar/', verbose_name='Banner Resmi (Dikey Önerilir)')),
                ('link', models.URLField(blank=True, verbose_name='Tıklayınca Gideceği Link')),
                ('pozisyon', models.CharField(choices=[('Sol', 'Sol Taraf'), ('Sag', 'Sağ Taraf')], default='Sol', max_length=10)),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
        ),
    ]
