# Generated by Django 6.0 on 2025-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reklambanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklambanner',
            name='resim',
            field=models.ImageField(help_text='📢 ÖNERİLEN BOYUT: Genişlik 200px x Yükseklik 600px (Dikey Resim). Farklı boyutta yüklerseniz tasarım bozulabilir.', upload_to='reklamlar/', verbose_name='Banner Resmi'),
        ),
    ]
