# Generated by Django 6.0 on 2025-12-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reklambanner_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='HukukKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kanunmaddesi',
            name='kanun_adi',
            field=models.CharField(default='Tanimlanmadi', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanunmaddesi',
            name='kanun_no',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanunmaddesi',
            name='madde_no',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='EmsalKarar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daire', models.CharField(max_length=100)),
                ('esas_no', models.CharField(max_length=50)),
                ('karar_no', models.CharField(max_length=50)),
                ('tarih', models.DateField(blank=True, null=True)),
                ('ozet', models.TextField()),
                ('tam_metin', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hukukkategori')),
            ],
        ),
        migrations.AddField(
            model_name='kanunmaddesi',
            name='kategori',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='core.hukukkategori'),
            preserve_default=False,
        ),
    ]
