# Generated by Django 6.0 on 2025-12-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hukukkategori_kanunmaddesi_kanun_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hukukkategori',
            name='aciklama',
            field=models.TextField(default='Bu alandaki kanun ve emsal kararlarla eğitilmiş uzman asistan.', max_length=300, verbose_name='Kart Açıklaması'),
        ),
        migrations.AddField(
            model_name='hukukkategori',
            name='ai_talimati',
            field=models.TextField(default='Sen bu alanda uzman, yardımsever bir hukuk asistanısın. Kanun maddelerine dayanarak cevap ver.', help_text="Örn: 'Sen sert mizaçlı bir ceza avukatısın' veya 'Sen çok açıklayıcı bir kira uzmanısın' gibi.", verbose_name='AI Gizli Talimatı (Prompt)'),
        ),
        migrations.AddField(
            model_name='hukukkategori',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Sitede Göster'),
        ),
        migrations.AddField(
            model_name='hukukkategori',
            name='ikon',
            field=models.CharField(default='⚖️', max_length=20, verbose_name='İkon (Emoji)'),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Link (Otomatik)'),
        ),
    ]
