# Generated by Django 6.0 on 2025-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hukukkategori_aciklama_hukukkategori_ai_talimati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklambanner',
            name='resim',
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='genislik',
            field=models.PositiveIntegerField(default=160, help_text='Örn: 160, 250, 300', verbose_name='Genişlik (px)'),
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='gorsel',
            field=models.ImageField(default='', upload_to='reklamlar/', verbose_name='Reklam Görseli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='yukseklik',
            field=models.PositiveIntegerField(default=600, help_text='Örn: 600, 250', verbose_name='Yükseklik (px)'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Sitede Görünsün mü?'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Reklam Adı'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Tıklanınca Gideceği Link'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='pozisyon',
            field=models.CharField(choices=[('Sol', 'Sol'), ('Sag', 'Sag')], max_length=10, verbose_name='Sayfadaki Yeri'),
        ),
    ]
