# Generated by Django 6.0 on 2025-12-07 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reklambanner_resim_reklambanner_genislik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparis',
            old_name='email',
            new_name='eposta',
        ),
        migrations.RenameField(
            model_name='siparis',
            old_name='adres',
            new_name='notlar',
        ),
        migrations.RemoveField(
            model_name='emsalkarar',
            name='daire',
        ),
        migrations.RemoveField(
            model_name='emsalkarar',
            name='esas_no',
        ),
        migrations.RemoveField(
            model_name='emsalkarar',
            name='karar_no',
        ),
        migrations.RemoveField(
            model_name='emsalkarar',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='emsalkarar',
            name='tam_metin',
        ),
        migrations.RemoveField(
            model_name='emsalkarar',
            name='tarih',
        ),
        migrations.RemoveField(
            model_name='kanunmaddesi',
            name='kanun_no',
        ),
        migrations.RemoveField(
            model_name='kanunmaddesi',
            name='konu',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_ai_balon',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_input_bg',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_user_balon',
        ),
        migrations.AddField(
            model_name='avukat',
            name='eposta',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='avukat',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avukatrandevu',
            name='eposta',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emsalkarar',
            name='baslik',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emsalkarar',
            name='dosya_linki',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paket',
            name='aciklama',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avukat',
            name='ozet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='avukat',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avukatrandevu',
            name='ad_soyad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avukatrandevu',
            name='avukat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avukat'),
        ),
        migrations.AlterField(
            model_name='avukatrandevu',
            name='durum',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Bekliyor', max_length=20),
        ),
        migrations.AlterField(
            model_name='avukatrandevu',
            name='mesaj',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='avukatrandevu',
            name='telefon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='ai_talimati',
            field=models.TextField(help_text='Bu kategorideki AI botuna verilecek özel gizli talimat.'),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='aktif_mi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='ikon',
            field=models.CharField(default='⚖️', max_length=50),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hukukkategori',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='kanunmaddesi',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hukukkategori'),
        ),
        migrations.AlterField(
            model_name='kanunmaddesi',
            name='madde_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paket',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paket',
            name='ozellikler',
            field=models.TextField(help_text='Her satıra bir özellik yazın'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='genislik',
            field=models.PositiveIntegerField(default=160, verbose_name='Genişlik (px)'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='yukseklik',
            field=models.PositiveIntegerField(default=600, verbose_name='Yükseklik (px)'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='font_baslik',
            field=models.CharField(default='Playfair Display', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='font_genel',
            field=models.CharField(default='Roboto', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_ana',
            field=models.CharField(default='#2c3e50', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_arkaplan',
            field=models.CharField(default='#f4f4f4', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_buton',
            field=models.CharField(default='#007bff', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_menu_bg',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_yazi_baslik',
            field=models.CharField(default='#333333', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_yazi_genel',
            field=models.CharField(default='#555555', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='site_basligi',
            field=models.CharField(default='HukukAI', max_length=200),
        ),
        migrations.AlterField(
            model_name='sohbetgecmisi',
            name='cevap',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sohbetgecmisi',
            name='soru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sohbetgecmisi',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
