# Generated by Django 5.2.9 on 2025-12-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_email_siparis_eposta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemBildirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('okundu_mu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('seviye', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('danger', 'Acil')], default='info', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_arkaplan',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_buton',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_menu_bg',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_yazi_baslik',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='renk_yazi_genel',
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='renk_arkaplan_dark',
            field=models.CharField(default='#202020', max_length=20, verbose_name='Koyu Mod Arkaplan'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='renk_arkaplan_light',
            field=models.CharField(default='#f5f5f7', max_length=20, verbose_name='Açık Mod Arkaplan'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='renk_kart_dark',
            field=models.CharField(default='#1c1c1e', max_length=20, verbose_name='Koyu Mod Kart Rengi'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='renk_kart_light',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Açık Mod Kart Rengi'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='renk_yazi_dark',
            field=models.CharField(default='#f5f5f7', max_length=20, verbose_name='Koyu Mod Yazı'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='renk_yazi_light',
            field=models.CharField(default='#1d1d1f', max_length=20, verbose_name='Açık Mod Yazı'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='font_baslik',
            field=models.CharField(choices=[('Inter', 'Inter (Modern & Temiz)'), ('Roboto', 'Roboto (Standart & Okunaklı)'), ('Open Sans', 'Open Sans (Ferah & Açık)'), ('Lato', 'Lato (Yuvarlak & Samimi)'), ('Montserrat', 'Montserrat (Geometrik & Güçlü)'), ('Raleway', 'Raleway (Zarif & İnce)'), ('Poppins', 'Poppins (Popüler & Yuvarlak)'), ('Playfair Display', 'Playfair Display (Tırnaklı & Klasik)'), ('Merriweather', 'Merriweather (Okuma Odaklı)'), ('Lora', 'Lora (Hukuki & Ciddi)'), ('Oswald', 'Oswald (Dik & Sıkışık)'), ('Rubik', 'Rubik (Yumuşak Köşeli)')], default='Inter', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='font_genel',
            field=models.CharField(choices=[('Inter', 'Inter (Modern & Temiz)'), ('Roboto', 'Roboto (Standart & Okunaklı)'), ('Open Sans', 'Open Sans (Ferah & Açık)'), ('Lato', 'Lato (Yuvarlak & Samimi)'), ('Montserrat', 'Montserrat (Geometrik & Güçlü)'), ('Raleway', 'Raleway (Zarif & İnce)'), ('Poppins', 'Poppins (Popüler & Yuvarlak)'), ('Playfair Display', 'Playfair Display (Tırnaklı & Klasik)'), ('Merriweather', 'Merriweather (Okuma Odaklı)'), ('Lora', 'Lora (Hukuki & Ciddi)'), ('Oswald', 'Oswald (Dik & Sıkışık)'), ('Rubik', 'Rubik (Yumuşak Köşeli)')], default='Inter', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='renk_ana',
            field=models.CharField(default='#0071e3', max_length=20, verbose_name='Ana Vurgu Rengi (Mavi vb.)'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='site_basligi',
            field=models.CharField(default='L.E.X.I.', max_length=200),
        ),
        migrations.CreateModel(
            name='VeriGuncellemeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('eklenen_veri_sayisi', models.IntegerField(default=0)),
                ('basarili_mi', models.BooleanField(default=True)),
                ('hata_mesaji', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hukukkategori')),
            ],
        ),
    ]
