# Generated by Django 5.2.9 on 2025-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sistembildirimi_remove_siteayarlari_renk_arkaplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklambanner',
            name='genislik',
            field=models.PositiveIntegerField(default=160, editable=False, verbose_name='Genişlik (px)'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Reklam Adı (Örn: Sol Taraf)'),
        ),
        migrations.AlterField(
            model_name='reklambanner',
            name='yukseklik',
            field=models.PositiveIntegerField(default=600, editable=False, verbose_name='Yükseklik (px)'),
        ),
    ]
